LINUX_PYTHON_INTERPRETER = "python3"
WINDOWS_PYTHON_INTERPRETER = "python"
DARWIN_PYTHON_INTERPRETER = "python3"
VENV_PYTHON_INTERPRETER = "python"

class OS:
    LINUX = "LINUX"
    WINDOWS = "WINDOWS"
    DARWIN = "DARWIN"
    VENV = "VENV"

class REQUESTS:
    GET = "GET"
    POST = "POST"

TOR_HTTP_PROXY_IP = "127.0.0.1"
TOR_HTTP_PROXY_PORT = "8118"
TOR_HTTP_PROXY_SCHEME = "https"
CHECK_TOR_PAGE = "https://check.torproject.org/"
TIMEOUT = 30
SCHEME = ""

CUSTOM_HEADER_INJECTION = False
CUSTOM_HEADER_NAME = ""
CUSTOM_HEADER_VALUE = ""


# Inject Tag
INJECT_TAG = "INJECT_HERE"
INJECT_TAG_REGEX = r"(?i)INJECT[_]?HERE"
VALUE_BOUNDARIES = r'[\\/](.+?)[\\/]'
INJECT_INSIDE_BOUNDARIES = None

TESTABLE_VALUE = ""

DEFAULT_TIME_OUT = 10
